# Generated by Django 2.2.15 on 2020-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='task_name',
        ),
    ]
