# Generated by Django 3.1.2 on 2020-11-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0002_auto_20201106_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='code',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
