# Generated by Django 2.2.15 on 2020-08-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0002_auto_20200815_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
