# Generated by Django 2.2.15 on 2020-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0003_delete_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='id',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='task_type_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
