# Generated by Django 2.2.15 on 2020-10-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0005_task_task_type'),
    ]

    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='TaskType',
            new_name='ExerciseType',
        ),
        migrations.RenameField(
            model_name='exercisetype',
            old_name='task_type_id',
            new_name='type_id',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Exercise',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('exercise_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='pyphone_app.Exercise')),
            ],
        ),
    ]
