# Generated by Django 3.1.2 on 2020-11-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0006_auto_20201112_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyphone_app.exercisetype'),
        ),
    ]
