# Generated by Django 2.2.15 on 2020-10-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyphone_app', '0007_auto_20201006_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BinaryField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyphone_app.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
