# Generated by Django 3.1.2 on 2020-11-27 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0008_userscourse_gainedpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscourse',
            name='finishDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userscourse',
            name='gainedPoints',
            field=models.FloatField(default=0),
        ),
    ]
