# Generated by Django 3.1.2 on 2020-11-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0010_auto_20201127_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscourse',
            name='finishDate',
        ),
    ]
