# Generated by Django 3.1.2 on 2020-11-27 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0012_userscourse_finishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 19, 14, 7, 429527)),
        ),
    ]
