# Generated by Django 3.1.2 on 2020-12-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0014_auto_20201127_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeName', models.CharField(max_length=100)),
                ('badgeDescription', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 14, 49, 25, 517640)),
        ),
    ]
