# Generated by Django 3.1.2 on 2020-12-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0015_auto_20201201_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 14, 49, 27, 656013)),
        ),
    ]
