# Generated by Django 3.1.2 on 2020-12-01 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0017_auto_20201201_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 15, 4, 34, 947532)),
        ),
    ]
