# Generated by Django 3.1.2 on 2020-12-01 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0018_auto_20201201_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='usersbadge',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 15, 31, 54, 99939)),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UsersBadge',
        ),
    ]
