# Generated by Django 3.1.2 on 2020-12-01 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0020_auto_20201201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievementType',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 20, 6, 26, 428149)),
        ),
    ]
