# Generated by Django 3.1.2 on 2020-12-02 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyphone_app', '0023_auto_20201201_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='possible_answers',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 20, 31, 53, 694010)),
        ),
    ]
